spring:
  application:
    name: compiler-service
  datasource:
    url: ${PGMQ_URL:jdbc:postgresql://localhost:5432/projectnil}
    username: ${PGMQ_USERNAME:projectnil}
    password: ${PGMQ_PASSWORD:projectnil}

compiler:
  language: assemblyscript
  job-queue: compilation_jobs
  result-queue: compilation_results
  timeout-ms: 10000
  poll-interval-ms: 1000

pgmq:
  url: ${PGMQ_URL:jdbc:postgresql://localhost:5432/projectnil}
  username: ${PGMQ_USERNAME:projectnil}
  password: ${PGMQ_PASSWORD:projectnil}
