name:  main

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs:
  check-test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: projectNIL

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check (checkstyle, spotbugs, javadoc)
        run: ./gradlew check

      - name: Run tests
        run: ./gradlew test

      - name: Build
        run: ./gradlew build

  deploy:
    needs: check-test-build 
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: deploy 
        run: echo "to be configured, scp image and podman compose"
